fix checks

diff --git a/.github/workflows/docker-image-check.yml b/.github/workflows/docker-image-check.yml
--- a/.github/workflows/docker-image-check.yml
+++ b/.github/workflows/docker-image-check.yml
@@ -39,15 +39,28 @@ jobs:
         echo "Testing Docker image on linux/amd64"
         docker run --platform linux/amd64 -d --name test-android-image-amd64 ${{ env.DOCKER_USERNAME }}/android-image:${{ github.sha }}
         sleep 10
+
+        # Check Appium server status
         echo "Checking Appium server status"
         if ! docker exec test-android-image-amd64 curl --fail http://localhost:4723/wd/hub/status; then
           echo "Appium server did not start successfully."
           docker logs test-android-image-amd64
+          docker stop test-android-image-amd64 || true
+          docker rm test-android-image-amd64 || true
           exit 1
         fi
         echo "Appium server is running."
-      env:
-        PLATFORM: linux/amd64
+
+        # Check if the emulator is running
+        echo "Checking if Android emulator is running"
+        if ! docker exec test-android-image-amd64 adb devices | grep -q "emulator"; then
+          echo "Error: No Android emulator is running."
+          docker logs test-android-image-amd64
+          docker stop test-android-image-amd64 || true
+          docker rm test-android-image-amd64 || true
+          exit 1
+        fi
+        echo "Android emulator is running."
 
     - name: Clean up
       run: |
