add health check

diff --git a/.github/workflows/docker-image-check.yml b/.github/workflows/docker-image-check.yml
--- a/.github/workflows/docker-image-check.yml
+++ b/.github/workflows/docker-image-check.yml
@@ -3,7 +3,7 @@ name: Check Docker Image Check
 on:
   pull_request:
     branches:
-      - master 
+      - master
 
 jobs:
   docker-build-run:
@@ -12,41 +12,49 @@ jobs:
       DOCKER_USERNAME: "mahmoudazaid"
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ env.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ env.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Build Docker image
-      run: |
-        docker build -t android-image:${{ github.sha }} .  
+      - name: Build Docker image
+        run: |
+          docker build -t android-image:${{ github.sha }} .
 
-    - name: Check if the Docker image runs
-      run: |
-        # Run the Docker container in detached mode
-        docker run -d -e APPIUM=true --name test-android-image android-image:${{ github.sha }}
-        
-        # Wait for the container to start
-        echo "Waiting for the container to start..."
-        sleep 10  
+      - name: Check if the Docker image runs
+        run: |
+          # Run the Docker container in detached mode
+          docker run -d -e APPIUM=true --name test-android-image android-image:${{ github.sha }}
 
-        if [[ $(docker ps -q -f name=test-android-image) ]]; then
-            echo "Container is up and running."
-        else
-            echo "Container failed to start."
-            exit 1
-        fi
+          # Wait for the container to start
+          echo "Waiting for the container to start..."
+          sleep 10  
 
-        docker logs test-android-image
+          if [[ $(docker ps -q -f name=test-android-image) ]]; then
+              echo "Container is up and running."
+          else
+              echo "Container failed to start."
+              exit 1
+          fi
 
-    - name: Clean up
-      run: |
-        docker stop test-android-image
-        docker rm test-android-image
+          container_health=$(docker inspect --format='{{.State.Health.Status}}' test-android-image)
+          if [[ "$container_health" == "healthy" ]]; then
+              echo "Container is healthy."
+          else
+              echo "Container is not healthy: $container_health"
+              exit 1
+          fi
+
+          docker logs test-android-image
+
+      - name: Clean up
+        run: |
+          docker stop test-android-image
+          docker rm test-android-image
