check container is running

diff --git a/.github/workflows/docker-image-check.yml b/.github/workflows/docker-image-check.yml
--- a/.github/workflows/docker-image-check.yml
+++ b/.github/workflows/docker-image-check.yml
@@ -30,9 +30,20 @@ jobs:
 
     - name: Check if the Docker image runs
       run: |
+        # Run the Docker container in detached mode
         docker run -d -e APPIUM=true --name test-android-image android-image:${{ github.sha }}
+        
+        # Wait for the container to start
+        echo "Waiting for the container to start..."
         sleep 10  
-        docker ps -a
+
+        if [[ $(docker ps -q -f name=test-android-image) ]]; then
+            echo "Container is up and running."
+        else
+            echo "Container failed to start."
+            exit 1
+        fi
+
         docker logs test-android-image
 
     - name: Clean up
